#!/bin/sh
PYTHON_BIN="$(git config --get wind3.python)"
if [ -z "$PYTHON_BIN" ]; then
  PYTHON_BIN=python
fi
exec "$PYTHON_BIN" .release/validate_release.py \
  --commit-message-file "$1" \
  --message-only
